# Generated by Django 5.1.6 on 2025-03-08 04:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bodycompositions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bodycompositionlog",
            name="body_fat",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(99.9),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="bodycompositionlog",
            name="weight",
            field=models.FloatField(
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(499.9),
                ]
            ),
        ),
    ]
