# Generated by Django 5.1.6 on 2025-03-08 04:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bodycompositions", "0002_alter_bodycompositionlog_body_fat_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bodymeasurements",
            name="biceps",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(99.9),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="bodymeasurements",
            name="calf",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(99.9),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="bodymeasurements",
            name="chest",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(149.9),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="bodymeasurements",
            name="hips",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(299.9),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="bodymeasurements",
            name="neck",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(49.9),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="bodymeasurements",
            name="thigh",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(99.9),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="bodymeasurements",
            name="waist",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(299.9),
                ],
            ),
        ),
    ]
