# Generated by Django 5.1.6 on 2025-03-03 05:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Exercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "muscle_group",
                    models.CharField(
                        choices=[
                            ("abdominals", "Abdominals"),
                            ("abductors", "Abductors"),
                            ("biceps", "Biceps"),
                            ("calves", "Calves"),
                            ("chest", "Chest"),
                            ("forearms", "Forearms"),
                            ("glutes", "Glutes"),
                            ("hamstrings", "Hamstrings"),
                            ("lats", "Lats"),
                            ("lower back", "Lower Back"),
                            ("middle back", "Middle Back"),
                            ("neck", "Neck"),
                            ("quadriceps", "Quadriceps"),
                            ("traps", "Traps"),
                            ("triceps", "Triceps"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=11,
                    ),
                ),
                (
                    "equipment",
                    models.CharField(
                        choices=[
                            ("dumbbell", "Dumbbell"),
                            ("bodyweight", "Bodyweight"),
                            ("barbell", "Barbell"),
                            ("cable", "Cable"),
                            ("e-z curl bar", "E Z Curl Bar"),
                            ("machine", "Machine"),
                            ("bands", "Bands"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=12,
                    ),
                ),
                ("exercise_picture", models.URLField(blank=True, null=True)),
                ("exercise_video", models.URLField(blank=True, null=True)),
                ("instructions", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ExerciseLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sets", models.PositiveSmallIntegerField()),
                ("repetitions", models.PositiveSmallIntegerField()),
                (
                    "rest_time",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=2, null=True
                    ),
                ),
                ("notes", models.TextField(blank=True, max_length=50, null=True)),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="workouts.exercise",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="WorkoutLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(blank=True)),
                (
                    "exercise_logs",
                    models.ManyToManyField(
                        related_name="workouts", to="workouts.exerciselog"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
