# Generated by Django 5.1.6 on 2025-03-01 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Exercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "MuscleGroup",
                    models.CharField(
                        choices=[
                            ("Abdominals", "Abdominals"),
                            ("Abductors", "Abductors"),
                            ("Biceps", "Biceps"),
                            ("Calves", "Calves"),
                            ("Chest", "Chest"),
                            ("Forearms", "Forearms"),
                            ("Glutes", "Glutes"),
                            ("Hamstrings", "Hamstrings"),
                            ("Lats", "Lats"),
                            ("Lower back", "Lower Back"),
                            ("Middle back", "Middle Back"),
                            ("Neck", "Neck"),
                            ("Quadriceps", "Quadriceps"),
                            ("Traps", "Traps"),
                            ("Triceps", "Triceps"),
                            ("Other", "Other"),
                        ],
                        default="Other",
                        max_length=11,
                    ),
                ),
                ("exercise_picture", models.URLField(blank=True, null=True)),
                ("exercise_video", models.URLField(blank=True, null=True)),
                ("instructions", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
