# Generated by Django 5.1.6 on 2025-03-03 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exerciselog",
            name="rest_time",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
