# Generated by Django 5.1.6 on 2025-03-01 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="exercise",
            old_name="MuscleGroup",
            new_name="muscle_group",
        ),
    ]
