# Generated by Django 5.1.6 on 2025-03-04 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0002_alter_exerciselog_rest_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exerciselog",
            name="sets",
        ),
    ]
