# Generated by Django 5.1.6 on 2025-03-01 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0002_rename_musclegroup_exercise_muscle_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercise",
            name="equipment",
            field=models.CharField(
                choices=[
                    ("dumbbell", "Dumbbell"),
                    ("bodyweight", "Bodyweight"),
                    ("barbell", "Barbell"),
                    ("cable", "Cable"),
                    ("e-z curl bar", "E Z Curl Bar"),
                    ("machine", "Machine"),
                    ("bands", "Bands"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="exercise",
            name="muscle_group",
            field=models.CharField(
                choices=[
                    ("abdominals", "Abdominals"),
                    ("abductors", "Abductors"),
                    ("biceps", "Biceps"),
                    ("calves", "Calves"),
                    ("chest", "Chest"),
                    ("forearms", "Forearms"),
                    ("glutes", "Glutes"),
                    ("hamstrings", "Hamstrings"),
                    ("lats", "Lats"),
                    ("lower back", "Lower Back"),
                    ("middle back", "Middle Back"),
                    ("neck", "Neck"),
                    ("quadriceps", "Quadriceps"),
                    ("traps", "Traps"),
                    ("triceps", "Triceps"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=11,
            ),
        ),
    ]
