# Generated by Django 5.1.6 on 2025-03-02 05:25

import django.db.models.deletion
import myFitnessApp.utils.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0003_exercise_equipment_alter_exercise_muscle_group"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExerciseLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sets", models.PositiveSmallIntegerField()),
                ("repetitions", models.PositiveSmallIntegerField()),
                (
                    "rest_time",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=2, null=True
                    ),
                ),
                ("notes", models.TextField(blank=True, max_length=50, null=True)),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="workouts.exercise",
                    ),
                ),
            ],
            bases=(
                models.Model,
                myFitnessApp.utils.mixins.HasUserMixin,
                myFitnessApp.utils.mixins.TimeStampedMixin,
            ),
        ),
        migrations.CreateModel(
            name="WorkoutLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True)),
                (
                    "exercise_logs",
                    models.ManyToManyField(
                        related_name="workouts", to="workouts.exerciselog"
                    ),
                ),
            ],
            bases=(
                models.Model,
                myFitnessApp.utils.mixins.HasUserMixin,
                myFitnessApp.utils.mixins.TimeStampedMixin,
            ),
        ),
    ]
