# Generated by Django 5.1.6 on 2025-03-04 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0003_remove_exerciselog_sets"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="workoutlog",
            options={"ordering": ["-created_at"]},
        ),
    ]
