# Generated by Django 5.1.6 on 2025-03-05 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0004_alter_workoutlog_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="exerciselog",
            name="weight",
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
