# Generated by Django 5.1.6 on 2025-03-16 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0006_alter_exercise_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="exercise",
            options={"ordering": ["name"]},
        ),
    ]
